config/routes.rb
Rails.application.routes.draw do
   # ユーザー用
  # URL /users/sign_in ...
  devise_for :users, skip: [:passwords],controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

root to: "public/homes#top"

scope module: :public do
  devise_scope :user do
    post 'users/guest_sign_in', to: 'sessions#guest_sign_in'
  end
  resources :users do
    resources :likes, only: [:index]
  end
  resources :reviews do
    resource :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
    collection do
      get :search
    end
  end
  resources :genres
  resources :tags

end


# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] , controllers: {
  sessions: "admin/sessions"
}

  namespace :admin do
    resources :users
    resources :comments
    resources :reviews
    resources :likes
    resources :genres
    resources :tags
    resources :admins
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :review

  validates :impression_comment, presence: true
end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :review
  validates_uniqueness_of :review_id, scope: :user_id
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user

  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :review_tags, dependent: :destroy
  has_many :tags, through: :review_tags

  has_one_attached :image

  validates :image, presence: true
  validates :title, presence: true
  validates :travel_comment, presence: true
  validates :evaluation, presence: true

  def liked_by?(user)
    likes.where(user_id: user.id).exists?
  end

  def save_tags(tags)

    # タグをスペース区切りで分割し配列にする
    #   連続した空白も対応するので、最後の“+”がポイント
    tag_list = tags.split(/[[:blank:]]+/)

    # 自分自身に関連づいたタグを取得する
    current_tags = self.tags.pluck(:tag_name)

    # (1) 元々自分に紐付いていたタグと投稿されたタグの差分を抽出
    #   -- 記事更新時に削除されたタグ
    old_tags = current_tags - tag_list

    # (2) 投稿されたタグと元々自分に紐付いていたタグの差分を抽出
    #   -- 新規に追加されたタグ
    new_tags = tag_list - current_tags

    p current_tags

    # tag_mapsテーブルから、(1)のタグを削除
    #   tagsテーブルから該当のタグを探し出して削除する
    old_tags.each do |old|
      # tag_mapsテーブルにあるpost_idとtag_idを削除
      #   後続のfind_byでtag_idを検索
      self.tags.delete Tag.find_by(tag_name: old)
    end

    # tagsテーブルから(2)のタグを探して、tag_mapsテーブルにtag_idを追加する
    new_tags.each do |new|
      # 条件のレコードを初めの1件を取得し1件もなければ作成する
      # find_or_create_by : https://railsdoc.com/page/find_or_create_by
      new_review_tag = Tag.find_or_create_by(tag_name: new)

      # tag_mapsテーブルにpost_idとtag_idを保存
      #   配列追加のようにレコードを渡すことで新規レコード作成が可能
      self.tags << new_review_tag
    end

  end
end

app/models/review_tag.rb
class ReviewTag < ApplicationRecord
  belongs_to :review
  belongs_to :tag

  validates :review_id, presence: true
  validates :tag_id, presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :reviews, dependent: :destroy

  has_many :review_tags, dependent: :destroy, foreign_key: 'tag_id'
  has_many :reviews, through: :review_tags
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :comments, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :members_status, inclusion: { in: [true, false] }

  def self.guest
    find_or_create_by!(nickname: 'ゲスト', email: 'guest@example.com') do |user|
      user.first_name = ""
      user.last_name = ""
      user.password = SecureRandom.urlsafe_base64
      # user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
      # 例えば name を入力必須としているならば， user.name = "ゲスト" なども必要
    end
  end

end

app/controllers/admin/passwords_controller.rb
# frozen_string_literal: true

class Admin::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/admin/reviews_controller.rb
class Admin::ReviewsController < ApplicationController

  def edit
    @review= Review.find(params[:id])
  end

  def update
     @review = Review.find(params[:id])
      if @review.update(review_params)
        redirect_to admin_users_path, notice: "更新されました。"
      else
        render "edit"
      end
  end

  def destroy
     @review = Review.find(params[:id])
      @review.destroy
      redirect_to admin_users_path
  end

   private

   def review_params
     params.require(:review).permit(:title, :travel_comment, )
   end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController

   protected


  def after_sign_in_path_for(resource)
   admin_users_path
  end

  def after_sign_out_path_for(resource)
   new_admin_session_path
  end
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @reviews = @user.reviews
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to admin_users_path
    else
      flash[:customer_updated_error] = "会員情報が正常に保存されませんでした。"
      redirect_to edit_admin_user_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:members_status)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :nickname, :email, :password])
  end

   #引数はuserとかでもオッケー
  def after_sign_up_path_for(resource)
    reviews_path
  end

  def after_sign_in_path_for(resource)
     reviews_path
  end

end

app/helpers/admin/admins_helper.rb
module Admin::AdminsHelper
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/likes_helper.rb
module Admin::LikesHelper
end

app/helpers/admin/reviews_helper.rb
module Admin::ReviewsHelper
end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/users/edit.html.erb
<div class="container">
    <h4 class="text-center", style="background-color:#eee; width:150px; margin:30px 0 30px 100px;">ユーザー編集</h4>
    <%= form_with model: @user, url: admin_user_path(@user.id), method: :patch, local: true  do |f| %>

    <%= render "public/shared/error_messages", resource: @user %>
    <div class="row">
      <div class="col-md-8 m-auto">
        <div class="form-group">
           <%= f.label :ニックネーム, style:"margin-right:86px;" %>
          <%= @user.nickname %>
        </div>
      <div class="row">
        <% if @user.email != "guest@example.com" %>
          <%= f.label :会員ステータス, class: "ml-3" %>
          <div class="form-check ml-4">
            <%= f.radio_button :members_status, :false %>
            <%= f.label :members_status, "有効会員" %>
            <%= f.radio_button :members_status, :true %>
            <%= f.label :members_status, "退会済み" %>
          </div>
        <% end %>
      </div>
      
      <% if @user.email != "guest@example.com" %>
        <div>
          <%= f.submit "保存する",class:"btn btn-success", style:"font-weight:bold; padding:5px 20px; margin:20px 20px 0 220px;" %>
        </div>
      <% end %>
      
      
      <div>
        <%= link_to '投稿一覧', admin_user_path(@user), class: "btn btn-success", style:"font-weight:bold; padding:5px 20px; margin:20px 20px 0 220px;" %>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/admin/users/index.html.erb
<div class='container'>
  <h4 class="text-center", style="background-color:#eee; width:120px; margin:20px "><b>会員一覧</b></h4>
	  <div class="row">
	    <div class="col-12">
		    <table class="table table-border", style="width:950px; margin: 0 auto; border-top:1px solid #bbb;">
		      <thead>
		        <tr style="background-color:#eee">
			        <th>ユーザーID</th>
				      <th>名前・ニックネーム</th>
				      <th>メールアドレス</th>
				      <th>ステータス</th>
			      </tr>
			     </thead>
			     <tbody>
			       <% @users.each do |user| %>
			         <tr>
				         <td><%= user.id %></td>
				         <td style>
				           <%= link_to edit_admin_user_path(user), style: "color: #000; text-decoration: underline;" do %>
					           <%= user.last_name %><%= user.first_name %>・<%= user.nickname %>
					         <% end %>
				         </td>
			           <td> <%= user.email %></td>
				         <td class="text-success font-weight-bold">
				           <% if user.members_status == false %>
                     有効
                   <% else %>
                     退会
                   <% end %>
                  </td>
                </tr>
              <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>

app/views/admin/users/show.html.erb
 <div class="album py-5 bg-light">
      <div class="container">
        <div class="row">
          <% @reviews.each do |review| %>
            <div class="col-md-4">
              <div class="card mb-4 shadow-sm">
                <%= link_to edit_admin_review_path(review), class:"text-dark"  do %>
                  <div class="card-deck">
                    <div class="card">
                      <%= image_tag review.image, class: "thumb-345-200" %>
                      <div class="card-body">
                        <h5 class="card-title"><%= review.title %></h5>
                        <p class="card-text"><%= review.travel_comment %></p>
                        <div id="evaluation<%= review.id%>"></div>
                        <script>
                          $('#evaluation<%= review.id %>').empty();
                          $('#evaluation<%= review.id%>').raty({
                          size      : 36,
                          starOff   : '<%= asset_path('star-off.png') %>',
                          starOn    : '<%= asset_path('star-on.png') %>',
                          starHalf  : '<%= asset_path('star-half.png') %>',
                          readOnly: true,
                          score: <%= review.evaluation %>,
                          });
                        </script>
                        <p class="mb-5"><strong><%= review.user.nickname %></strong></p>
                      </div>
                    </div>
                  </div>
                <% end %>
              </div>
            </div>
          <% end %>
      </div>
    </div>