config/routes.rb
Rails.application.routes.draw do
   # ユーザー用
  # URL /users/sign_in ...
  devise_for :users, skip: [:passwords],controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

root to: "public/homes#top"

scope module: :public do
  devise_scope :user do
    post 'users/guest_sign_in', to: 'sessions#guest_sign_in'
  end
  resources :users do
    resources :likes, only: [:index]
  end
  resources :reviews do
    resource :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
    collection do
      get :search
    end
  end
  resources :genres
  resources :tags

end


# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] , controllers: {
  sessions: "admin/sessions"
}

  namespace :admin do
    resources :users
    resources :comments
    resources :reviews
    resources :likes
    resources :genres
    resources :tags
    resources :admins
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :review

  validates :impression_comment, presence: true
end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :review
  validates_uniqueness_of :review_id, scope: :user_id
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user

  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :review_tags, dependent: :destroy
  has_many :tags, through: :review_tags

  has_one_attached :image

  validates :image, presence: true
  validates :title, presence: true
  validates :travel_comment, presence: true
  validates :evaluation, presence: true

  def liked_by?(user)
    likes.where(user_id: user.id).exists?
  end

  def save_tags(tags)

    # タグをスペース区切りで分割し配列にする
    #   連続した空白も対応するので、最後の“+”がポイント
    tag_list = tags.split(/[[:blank:]]+/)

    # 自分自身に関連づいたタグを取得する
    current_tags = self.tags.pluck(:tag_name)

    # (1) 元々自分に紐付いていたタグと投稿されたタグの差分を抽出
    #   -- 記事更新時に削除されたタグ
    old_tags = current_tags - tag_list

    # (2) 投稿されたタグと元々自分に紐付いていたタグの差分を抽出
    #   -- 新規に追加されたタグ
    new_tags = tag_list - current_tags

    p current_tags

    # tag_mapsテーブルから、(1)のタグを削除
    #   tagsテーブルから該当のタグを探し出して削除する
    old_tags.each do |old|
      # tag_mapsテーブルにあるpost_idとtag_idを削除
      #   後続のfind_byでtag_idを検索
      self.tags.delete Tag.find_by(tag_name: old)
    end

    # tagsテーブルから(2)のタグを探して、tag_mapsテーブルにtag_idを追加する
    new_tags.each do |new|
      # 条件のレコードを初めの1件を取得し1件もなければ作成する
      # find_or_create_by : https://railsdoc.com/page/find_or_create_by
      new_review_tag = Tag.find_or_create_by(tag_name: new)

      # tag_mapsテーブルにpost_idとtag_idを保存
      #   配列追加のようにレコードを渡すことで新規レコード作成が可能
      self.tags << new_review_tag
    end

  end
end

app/models/review_tag.rb
class ReviewTag < ApplicationRecord
  belongs_to :review
  belongs_to :tag

  validates :review_id, presence: true
  validates :tag_id, presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :reviews, dependent: :destroy

  has_many :review_tags, dependent: :destroy, foreign_key: 'tag_id'
  has_many :reviews, through: :review_tags
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :comments, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :members_status, inclusion: { in: [true, false] }

  def self.guest
    find_or_create_by!(nickname: 'ゲスト', email: 'guest@example.com') do |user|
      user.first_name = ""
      user.last_name = ""
      user.password = SecureRandom.urlsafe_base64
      # user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
      # 例えば name を入力必須としているならば， user.name = "ゲスト" なども必要
    end
  end

end

app/controllers/admin/reviews_controller.rb
class Admin::ReviewsController < ApplicationController

  def edit
    @review= Review.find(params[:id])
  end

  def update
     @review = Review.find(params[:id])
      if @review.update(review_params)
        redirect_to admin_users_path, notice: "更新されました。"
      else
        render "edit"
      end
  end

  def destroy
     @review = Review.find(params[:id])
      @review.destroy
      redirect_to admin_users_path
  end

   private

   def review_params
     params.require(:review).permit(:title, :travel_comment, )
   end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @reviews = @user.reviews
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to admin_users_path
    else
      flash[:customer_updated_error] = "会員情報が正常に保存されませんでした。"
      redirect_to edit_admin_user_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:members_status)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :nickname, :email, :password])
  end

   #引数はuserとかでもオッケー
  def after_sign_up_path_for(resource)
    reviews_path
  end

  def after_sign_in_path_for(resource)
     reviews_path
  end

end

app/helpers/admin/admins_helper.rb
module Admin::AdminsHelper
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/likes_helper.rb
module Admin::LikesHelper
end

app/helpers/admin/reviews_helper.rb
module Admin::ReviewsHelper
end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_flash.html.erb
<div class="text-success", style="background-color: #CC99CC;">
  <%= flash[:notice] %>
</div>
<div class="text-danger">
  <%= flash[:alret] %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hitotabi1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <header>
    <nav class="navbar navbar-expand navbar-dark navbar-fixed-top", style="background-color: #FF9872;">
      <div class="container">
        <% if user_signed_in? %>
          <h1 class="", style="font-weight:bold;">
            <%= link_to "ひとたび", reviews_path, class: "navbar-brand" %>
          </h1>
          <span class="u h7 text-white strong">
            ようこそ！<%= current_user.nickname %>さん！
          </span>
          <ul class="navbar-nav">
            <li class="nav-item">
              <button type="button" class="btn btn-warning btn-sm", style="margin-right:30px">
                <%= link_to "レビューを投稿する", new_review_path, class: "nav-link" %>
              </button>
            </li>
            <li class="nav-item">
              <button type="button" class="btn btn-warning btn-sm", style="margin-right:30px">
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-link" %>
              </button>
            </li>
          </ul>
          
          <% elsif admin_signed_in? %>
          <h1 class="", style="font-weight:bold;">
            <%= link_to "ひとたび", admin_users_path, class: "navbar-brand" %>
          </h1>
          <ul class="navbar-nav">
            <li class="nav-item">
              <div class="r-2">
                <button type="button" class="btn btn-warning btn-sm", style="margin-right:30px">
                  <%= link_to "ユーザー一覧", admin_users_path, class: "nav-link" %>
                </button>
              </div>
            </li>
            <li class="nav-item">
              <button type="button" class="btn btn-warning btn-sm">
                <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "nav-link" %>
              </button>
            </li>
          </ul>
          <% else %>
          <h1 class="", style="font-weight:bold;">
            <%= link_to "ひとたび", root_path, class: "navbar-brand" %>
          </h1>
          <span class="u h7 text-white strong">
            ようこそ! ひとたびへ
          </span>
          <ul class="navbar-nav">
            <li class="nav-item">
              <div class="r-2">
                <button type="button" class="btn btn-warning btn-sm", style="margin-right:30px">
                  <%= link_to "ゲストログイン", users_guest_sign_in_path, method: :post, class: "nav-link" %>
                </button>
              </div>
            </li>
            <li class="nav-item">
              <button type="button" class="btn btn-warning btn-sm", style="margin-right:30px">
                <%= link_to "新規登録", new_user_registration_path, class: "nav-link" %>
              </button>
            </li>
            <li class="nav-item">
              <button type="button" class="btn btn-warning btn-sm">
                <%= link_to "ログイン", new_user_session_path, class: "nav-link" %>
              </button>
            </li>
          </ul>
        <% end %>
      </div>
    </nav>
  </header>
  <%= yield %>
  <footer class="text-muted">
    <div class="container">
      <p class="float-center">
        ひとたび
      </p>
    </div>
  </footer>
</html>